[package]
name = "sneck"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {version = "0.17", features = ["file_watcher"]}
strum = "*"
strum_macros = "*"
rand = "*"
# bevy_granite = { path = "Y:/dependencies/bevy_granite" }
leafwing-input-manager = "0.19.0"
thiserror = "*"

[features]
default = ["streamer_mode"]
streamer_mode = []

[profile.dev.package."*"]
opt-level = 3